### ISSUE TITLE
Roll over hub data logs daily

### ISSUE THREAD

**Issue by jordanreedie** [HumanDynamics/openbadge-server#36]
https://github.com/HumanDynamics/openbadge-server/blob/28d90aa4eed39eb05b0ba55df298edcaebdd074f/openbadge-server/openbadge/views.py#L363-L423

**Comment by jordanreedie** [comment]
here's what i see:
- we need to change datafile_uuid to hub name + type + date
- we need to change the method for getting datafile objects to return the most recent object for a provided hub name + type when passed no arguments
- we check the log_timestamp of the first chunk provided. if it is on the same day as the existing datafile, we carry on. if not, create a new datafile.
- as we iterate through the chunks, we check to make sure each chunk is from the same day. if we see a chunk from a day more recent than the one indicated by the current datafile, we create a new datafile and continue from where we left off

does that sound right?

**Comment by jordanreedie** [comment]
@OrenLederman

**Comment by OrenLederman** [comment]
It might be more tricky than that - for a single badge, the data from the hub will be sequential. But, the hub gets data from multiple badges, so in the same file there could be, potentially, data from different dates, out of order. So we need to be able to go back and forth. 

Another option is to store data based on when the server received the data. This should simplify the code significantly. If we really want to manage the data itself by dates, we should store the data in a database..

Other notes:
* We don't want to open and close files for each chunk/line of data. that'll be slow. Instead, we'll only close file a open a new one if the date changes
* There is a file field type that we'll might want to use instead of just a text. I think it will make it easier to manage the location of the files (/media/data). Note that I think there's a bug in the dev mode where data isn't really being saved to the media folder

**Comment by jordanreedie** [comment]
i think we could fix that by pretty easily by sorting incoming data by date - i dont think it would slow us down too much at our scale. this way we write all data to oldest file, then next oldest, etc. shouldnt have to open/close each file more than once

but yeah, i think this issue is most cleanly solved by just using an actual database.

how soon do you want/need this up and running?

ps i'll check out the dev mode bug

**Comment by OrenLederman** [comment]
Ideally I'd like ot have it ready and tested before the summer experiment, which means that a database implementation won't make it in time (and way too risky right now).

The reason I want something like this now is so that I can generate daily usage/compliance reports. I'd rather avoid downloading the entire historical file every day.

Sorting takes memory, so we need to be careful. We already allocate a lot of memory for this, right? (though you limit the size of the file we submit at once). But yes... sorting is not a bad idea.  

Oh, by the way - we need to keep in mind the timezones. If we work in UTC it can be confusing when we look for the data.

Because the experiment is very close, I think that simply saving data base don the date of arrival is good enough. In our setting, there's usually good coverage and we'll only get old data if the badge was out of range (someone took it home). It's much easier and safe to implement. don't you think?
